create table Cricketers(
	cricketers_id serial primary key,
	first_name varchar(100),
	last_name varchar(100),
	gender varchar(50),
	country varchar(100)
)

select * from cricketers

insert into cricketers(cricketers_id,first_name,last_name,gender,country) values (1,'Hamel', 'O''Neill', 'Male', 'Norway')
insert into cricketers(cricketers_id,first_name,last_name,gender,country) values(2,'Josefa', 'Petchell', 'Female', 'Germany')
insert into cricketers(cricketers_id,first_name,last_name,gender,country) values(3,'Manya', 'Yushmanov', 'Female', 'Kosovo'),
(4,'Weber', 'Hallowes', 'Male', 'China'),
(5,'Allissa', 'Rogister', 'Female', 'Indonesia'),
(6,'Doria', 'Neicho', 'Female', 'Chad'),
(7,'Simeon', 'O''Spillane', 'Male', 'Albania'),
(8,'Renae', 'Harp', 'Female', 'Afghanistan'),
(9,'Travus', 'L''Archer', 'Male', 'Cuba'),
(10,'Nedi', 'Gath', 'Female', 'American Samoa'),
(11,'Kelley', 'Strahan', 'Female', 'France'),
(12,'Salomon', 'Cantillion', 'Male', 'Uzbekistan'),
(13,'Bail', 'Saph', 'Male', 'Cuba'),
(14,'Jeanine', 'Bilsford', 'Polygender', 'Philippines'),
(15,'Betty', 'Duchan', 'Female', 'Thailand'),
(16,'Timothy', 'Champney', 'Male', 'Indonesia'),
(17,'Alberto', 'Nanuccioi', 'Male', 'Finland'),
(18,'Gayla', 'Cranston', 'Female', 'United States'),
(19,'Luther', 'Kimpton', 'Male', 'Japan'),
(20,'Thorny', 'Doman', 'Male', 'Thailand'),
(21,'Dolores', 'Jeanenet', 'Female', 'China'),
(22,'Stearne', 'Houlden', 'Male', 'South Africa'),
(23,'Errol', 'Casarini', 'Male', 'Kuwait'),
(24,'Lark', 'Tash', 'Non-binary', 'China'),
(25,'Pauli', 'Pehrsson', 'Female', 'United States'),
(26,'Hershel', 'Haseley', 'Non-binary', 'China'),
(27,'Amandi', 'Laflin', 'Polygender', 'Russia'),
(28,'Ashleigh', 'Hebborn', 'Female', 'Russia'),
(29,'Kendrick', 'Pechacek', 'Male', 'Philippines'),
(30,'Ham', 'Dodgshon', 'Male', 'Ethiopia'),
(31,'Dimitry', 'Najara', 'Male', 'Brazil'),
(32,'Dulcea', 'Frugier', 'Female', 'Indonesia'),
(33,'Vergil', 'Cordobes', 'Male', 'China'),
(34,'Gustav', 'Reyne', 'Male', 'China'),
(35,'Brewster', 'Brogini', 'Male', 'Madagascar'),
(36,'Josi', 'MacDonald', 'Female', 'Iran'),
(37,'Dani', 'Houlden', 'Male', 'Netherlands'),
(38,'Udell', 'Weber', 'Male', 'Mongolia'),
(39,'Issi', 'Rizzelli', 'Female', 'South Korea'),
(40,'Jerrie', 'Gebhardt', 'Male', 'Vietnam'),
(41,'Aubrette', 'Spratley', 'Female', 'China'),
(42,'Camey', 'Stansbury', 'Male', 'China'),
(43,'Garek', 'Tunaclift', 'Male', 'El Salvador'),
(44,'Noelyn', 'Rydings', 'Female', 'United States'),
(45,'Dreddy', 'Stairs', 'Female', 'Japan'),
(46,'Drucy', 'Tammadge', 'Female', 'Vietnam'),
(47,'Dehlia', 'Lassells', 'Female', 'Indonesia'),
(48,'Katrina', 'Benne', 'Female', 'United States'),
(49,'Erroll', 'Lamas', 'Male', 'Poland'),
(50,'Bradley', 'Scurman', 'Male', 'Greece'),
(51,'Keriann', 'Grisley', 'Female', 'Iraq'),
(52,'Marve', 'Calles', 'Male', 'China'),
(53,'Free', 'Southby', 'Male', 'Dominican Republic'),
(54,'Nicol', 'Duffett', 'Female', 'Kazakhstan'),
(55,'Vasily', 'Lorent', 'Male', 'Spain'),
(56,'Rudyard', 'De La Coste', 'Male', 'Russia'),
(57,'Bria', 'Huccaby', 'Female', 'Thailand'),
(58,'Delores', 'Galier', 'Female', 'Philippines'),
(59,'Merralee', 'Seaborn', 'Female', 'Russia'),
(60,'Thor', 'Greatex', 'Male', 'China'),
(61,'Renaud', 'Piddle', 'Male', 'Tunisia'),
(62,'Jeremie', 'Ranklin', 'Male', 'Indonesia'),
(63,'Marcille', 'Crusham', 'Female', 'China'),
(64,'Kristo', 'Gilfoyle', 'Male', 'Brazil'),
(65,'Talyah', 'Vater', 'Female', 'Russia'),
(66,'Dyane', 'Horney', 'Bigender', 'China'),
(67,'Shane', 'Baudinot', 'Male', 'Greece'),
(68,'Sherill', 'Raiment', 'Female', 'Russia'),
(69,'Honey', 'Ferrero', 'Bigender', 'China'),
(70,'Eleanora', 'Cromer', 'Female', 'France'),
(71,'Gradeigh', 'Shiers', 'Male', 'Central African Republic'),
(72,'Doll', 'Walch', 'Female', 'Philippines'),
(73,'Padraig', 'Offin', 'Male', 'Indonesia'),
(74,'Masha', 'Corcut', 'Polygender', 'Russia'),
(75,'Clarabelle', 'Neljes', 'Genderfluid', 'Yemen'),
(76,'Janot', 'Paoletti', 'Female', 'China'),
(77,'Kingston', 'Maddy', 'Male', 'Belarus'),
(78,'Rose', 'Nobles', 'Female', 'Brazil'),
(79,'Lynda', 'McLugish', 'Female', 'Greece'),
(80,'Jameson', 'Fassan', 'Male', 'China'),
(81,'Andriette', 'Udall', 'Female', 'China'),
(82,'Nevins', 'Grishukhin', 'Male', 'Portugal'),
(83,'Reube', 'Samsworth', 'Male', 'Tanzania'),
(84,'Dari', 'Gulston', 'Female', 'Myanmar'),
(85,'Nathaniel', 'Benns', 'Male', 'Hungary'),
(86,'Lorin', 'Lavens', 'Male', 'Dominican Republic'),
(87,'Henderson', 'Dorton', 'Male', 'China'),
(88,'Leandra', 'Thurston', 'Female', 'China'),
(89,'Willey', 'Hark', 'Male', 'China'),
(90,'Jessamine', 'Karolovsky', 'Female', 'Indonesia'),
(91,'Corilla', 'Venners', 'Female', 'Taiwan'),
(92,'Nettie', 'Blackway', 'Female', 'Slovenia'),
(93,'Raina', 'Youd', 'Female', 'Philippines'),
(94,'Cameron', 'Cleever', 'Male', 'Peru'),
(95,'Valerie', 'Fashion', 'Female', 'United States'),
(96,'Alvinia', 'Evason', 'Female', 'China'),
(97,'Friederike', 'Merit', 'Female', 'Bulgaria'),
(98,'Quinn', 'Benjefield', 'Female', 'Morocco'),
(99,'Tabby', 'Caffery', 'Male', 'Russia'),
(100,'Pennie', 'Standage', 'Male', 'China')

	select * from cricketers

insert into cricketers(cricketers_id,first_name,last_name,gender,country) values(101,'Lyndsie', 'Rippen', 'Female', 'Latvia'),
(102,'Benny', 'Borrington', 'Female', 'Afghanistan'),
(103,'Anatollo', 'Mantrip', 'Male', 'South Africa'),
(104,'Raf', 'Narducci', 'Female', 'Indonesia'),
(105,'Bren', 'Dobrovolski', 'Female', 'France'),
(106,'Jeni', 'Cristofor', 'Bigender', 'Russia'),
(107,'Jilly', 'Hubback', 'Female', 'Madagascar'),
(108,'Ketti', 'Lofting', 'Female', 'China'),
(109,'Loria', 'McFetridge', 'Female', 'France'),
(110,'Georg', 'Marconi', 'Male', 'French Southern Territories'),
(111,'Perice', 'Uc', 'Male', 'China'),
(112,'Milo', 'Carff', 'Male', 'Russia'),
(113,'Lesya', 'Osgardby', 'Female', 'South Africa'),
(114,'Jean', 'Child', 'Male', 'China'),
(115,'Reynold', 'Kearley', 'Male', 'China'),
(116,'Joaquin', 'Sooley', 'Male', 'Indonesia'),
(117,'Robinette', 'Suter', 'Female', 'Philippines'),
(118,'Averil', 'Flintoft', 'Female', 'Peru'),
(119,'Ronnie', 'Crommett', 'Female', 'Japan'),
(120,'Colas', 'Sidebotham', 'Male', 'Brazil'),
(121,'Paquito', 'Maisey', 'Male', 'Poland'),
(122,'Lennard', 'Arendsen', 'Genderfluid', 'United States'),
(123,'Kym', 'Asaaf', 'Female', 'Indonesia'),
(124,'Jacenta', 'Pesik', 'Female', 'Sweden'),
(125,'Tessy', 'Houlton', 'Female', 'Brazil'),
(126,'Mehetabel', 'McConigal', 'Female', 'Canada'),
(127,'Olly', 'Hellwich', 'Male', 'Indonesia'),
(128,'Chickie', 'Yepiskov', 'Female', 'Indonesia'),
(129,'Johny', 'Barkworth', 'Male', 'Russia'),
(130,'Gracia', 'Phibb', 'Female', 'Tanzania'),
(131,'Saw', 'Burnip', 'Male', 'Kazakhstan'),
(132,'Emanuele', 'Johansson', 'Male', 'France'),
(133,'Shea', 'Powys', 'Male', 'Indonesia'),
(134,'Jan1essa', 'Wigelsworth', 'Female', 'China'),
(135,'Henrieta', 'Smaling', 'Female', 'Poland'),
(136,'Guillema', 'Peachman', 'Female', 'Croatia'),
(137,'Prisca', 'Briston', 'Female', 'Spain'),
(138,'Aviva', 'Jellings', 'Bigender', 'Indonesia'),
(139,'Bealle', 'Braben', 'Male', 'Macedonia'),
(140,'Nichole', 'Binner', 'Male', 'Dominican Republic'),
(141,'Sterling', 'Poultney', 'Male', 'China'),
(142,'Agosto', 'Brickhill', 'Male', 'China'),
(143,'Oralie', 'Frankland', 'Female', 'Indonesia'),
(144,'Corabella', 'McConnulty', 'Female', 'Japan'),
(145,'Bartlet', 'Thys', 'Agender', 'France'),
(146,'Roma', 'De Brett', 'Male', 'Brazil'),
(147,'Fawnia', 'Broadist', 'Female', 'Philippines'),
(148,'Darrell', 'Kneafsey', 'Male', 'Germany'),
(149,'Theodore', 'Wheatland', 'Male', 'China'),
(150,'Niven', 'Yankov', 'Male', 'Philippines'),
(151,'Marybeth', 'Hellewell', 'Agender', 'Indonesia'),
(152,'Lyle', 'Broyd', 'Male', 'Nicaragua'),
(153,'Shauna', 'Grancher', 'Female', 'Philippines'),
(154,'Carmella', 'Conor', 'Female', 'Portugal'),
(155,'Ange', 'Hambleton', 'Male', 'South Africa'),
(156,'Haydon', 'Downe', 'Male', 'Brazil'),
(157,'Carlye', 'O''Regan', 'Female', 'Russia'),
(158,'Stewart', 'Possek', 'Male', 'Canada'),
(159,'Karl', 'Jeger', 'Male', 'Slovenia'),
(160,'Virge', 'Verni', 'Male', 'China'),
(161,'Alair', 'Plaunch', 'Male', 'Indonesia'),
(162,'Enrique', 'Leedal', 'Male', 'Russia'),
(163,'Georgette', 'Ingledew', 'Female', 'Vietnam'),
(164,'Anson', 'Richt', 'Male', 'Chile'),
(165,'Henderson', 'Mackinder', 'Male', 'Zambia'),
(166,'Bobina', 'Apfelmann', 'Female', 'France'),
(167,'Tani', 'Minchinden', 'Female', 'Indonesia'),
(168,'Corrie', 'Babon', 'Male', 'Slovenia'),
(169,'Bartie', 'Chilvers', 'Male', 'Philippines'),
(170,'Dayle', 'Fliege', 'Genderqueer', 'Philippines'),
(171,'Richy', 'Kliment', 'Male', 'Indonesia'),
(172,'Bradford', 'Widdocks', 'Male', 'Argentina'),
(173,'Annette', 'Dawdry', 'Female', 'Philippines'),
(174,'Eveleen', 'McElvogue', 'Female', 'Tanzania'),
(175,'Wade', 'Murfin', 'Male', 'Vietnam'),
(176,'Hartwell', 'Derisley', 'Male', 'Spain'),
(177,'Elaina', 'Maccaddie', 'Female', 'Papua New Guinea'),
(178,'Roldan', 'McNaughton', 'Agender', 'Honduras'),
(179,'Prince', 'Trumpeter', 'Male', 'Mongolia'),
(180,'Bernard', 'Peron', 'Male', 'Madagascar'),
(181,'Terry', 'Pryell', 'Female', 'Indonesia'),
(182,'Sigfried', 'Jindracek', 'Male', 'Japan'),
(183,'Earl', 'Fernanando', 'Male', 'Brazil'),
(184,'Skipper', 'Kubec', 'Male', 'China'),
(185,'Ines', 'Neggrini', 'Female', 'China'),
(186,'Barnebas', 'Barense', 'Male', 'Lithuania'),
(187,'Clyde', 'Errett', 'Male', 'Czech Republic'),
(188,'Maje', 'Freckingham', 'Male', 'Argentina'),
(189,'Herrick', 'Macconaghy', 'Male', 'France'),
(190,'Reinwald', 'McCooke', 'Male', 'Philippines'),
(191,'Nataniel', 'Suter', 'Bigender', 'Pakistan'),
(192,'Gayle', 'Godbolt', 'Female', 'Brazil'),
(193,'Sonni', 'Newgrosh', 'Female', 'Brazil'),
(194,'Dodie', 'Ramble', 'Bigender', 'China'),
(195,'Ettore', 'Tyne', 'Male', 'Poland'),
(196,'Em', 'Farron', 'Male', 'Russia'),
(197,'Kayne', 'Lindfors', 'Male', 'Greece'),
(198,'Barnabe', 'Assaf', 'Male', 'Cambodia'),
(199,'Kim', 'Breit', 'Male', 'Brazil'),
(200,'Inglebert', 'Willmett', 'Male', 'China')

	select * from cricketers

insert into cricketers(cricketers_id,first_name,last_name,gender,country) values(201,'Corly', 'Heller', 'Bigender', 'Indonesia'),
(202,'Carolan', 'Caustic', 'Female', 'Serbia'),
(203,'Lory', 'Bauduin', 'Female', 'United States'),
(204,'Briant', 'Roncelli', 'Male', 'Dominican Republic'),
(205,'Yvette', 'Ivasyushkin', 'Female', 'Philippines'),
(206,'Dilly', 'Atkinson', 'Male', 'Kuwait'),
(207,'Georgy', 'Bonnette', 'Male', 'Guatemala'),
(208,'Winonah', 'Gurg', 'Female', 'Laos'),
(209,'Erroll', 'Stonelake', 'Male', 'Portugal'),
(210,'Gideon', 'Kingswood', 'Male', 'United States'),
(211,'Reagen', 'Kennan', 'Male', 'Poland'),
(212,'Salomone', 'Inseal', 'Male', 'Thailand'),
(213,'Jorrie', 'Barbier', 'Female', 'China'),
(214,'Urson', 'Guarin', 'Male', 'Laos'),
(215,'Leslie', 'Auston', 'Bigender', 'Bolivia'),
(216,'Glynn', 'Jearum', 'Male', 'Netherlands'),
(217,'Dalia', 'Malone', 'Female', 'Brazil'),
(218,'Brittni', 'Syncke', 'Female', 'Philippines'),
(219,'Kass', 'Bonnick', 'Female', 'Ukraine'),
(220,'Sloan', 'Grzelak', 'Male', 'China'),
(221,'Kaylil', 'Stivers', 'Female', 'Estonia'),
(222,'Ingra', 'McRorie', 'Male', 'Germany'),
(223,'Barnebas', 'Ladon', 'Male', 'China'),
(224,'Daron', 'Sweed', 'Female', 'Armenia'),
(225,'Purcell', 'Roma', 'Male', 'Colombia'),
(226,'Terza', 'Currey', 'Female', 'Indonesia'),
(227,'Jolene', 'MacCaffery', 'Genderfluid', 'Croatia'),
(228,'Chrissie', 'Poulsum', 'Male', 'Indonesia'),
(229,'Fanny', 'Booty', 'Female', 'Sweden'),
(230,'Leonid', 'Bolens', 'Male', 'Portugal'),
(231,'Caye', 'Pontefract', 'Polygender', 'China'),
(232,'Gayle', 'Phillipson', 'Male', 'Japan'),
(233,'Halsey', 'Beevors', 'Male', 'Portugal'),
(234,'Stu', 'Levensky', 'Male', 'Egypt'),
(235,'Bertrand', 'Audrey', 'Male', 'Oman'),
(236,'Nerty', 'Spatoni', 'Female', 'Poland'),
(237,'Mattias', 'Vallery', 'Male', 'China'),
(238,'North', 'Flewin', 'Bigender', 'United States'),
(239,'Hetti', 'Shurey', 'Female', 'Portugal'),
(240,'Janek', 'Moxom', 'Male', 'Luxembourg'),
(241,'Pierrette', 'Kanwell', 'Female', 'Poland'),
(242,'Christiane', 'Danelet', 'Female', 'China'),
(243,'Sonia', 'Josovitz', 'Female', 'China'),
(244,'Eileen', 'Stener', 'Non-binary', 'Portugal'),
(245,'Ajay', 'Cheese', 'Female', 'China'),
(246,'Berry', 'Edgington', 'Female', 'United States'),
(247,'Hamel', 'Killiner', 'Male', 'Czech Republic'),
(248,'Brita', 'Fiddyment', 'Female', 'China'),
(249,'Marlee', 'Rosensaft', 'Female', 'France'),
(250,'Adler', 'Soanes', 'Male', 'Sweden'),
(251,'Karlik', 'Rutt', 'Male', 'Russia'),
(252,'Tandie', 'Parman', 'Female', 'Venezuela'),
(253,'Genvieve', 'Trorey', 'Female', 'Portugal'),
(254,'Clint', 'Gerram', 'Male', 'Canada'),
(255,'Hurleigh', 'Houston', 'Genderqueer', 'Indonesia'),
(256,'Christy', 'Torrijos', 'Female', 'China'),
(257,'Cory', 'Van der Beek', 'Female', 'United States'),
(258,'Simone', 'Aspell', 'Male', 'Russia'),
(259,'Angeli', 'Jamrowicz', 'Genderfluid', 'Russia'),
(260,'Joe', 'Drabble', 'Genderfluid', 'Portugal'),
(261,'Jannel', 'Quadri', 'Female', 'China'),
(262,'Frederick', 'Scurfield', 'Male', 'Kazakhstan'),
(263,'Kristoffer', 'Winder', 'Male', 'Portugal'),
(264,'Christal', 'Dubble', 'Female', 'Russia'),
(265,'Tim', 'Menere', 'Male', 'Costa Rica'),
(266,'Terrye', 'Rhoddie', 'Bigender', 'China'),
(267,'Ulrich', 'Molesworth', 'Male', 'Indonesia'),
(268,'Sibilla', 'Laise', 'Female', 'Syria'),
(269,'Berk', 'Todd', 'Male', 'Indonesia'),
(270,'Fidel', 'Low', 'Male', 'Russia'),
(271,'Orelee', 'Rigby', 'Female', 'Finland'),
(272,'Carey', 'Diche', 'Female', 'Nigeria'),
(273,'Noble', 'Bailey', 'Male', 'Benin'),
(274,'Jana', 'Rainbow', 'Female', 'Albania'),
(275,'Abran', 'Statter', 'Male', 'Russia'),
(276,'Griz', 'Mapowder', 'Male', 'Spain'),
(277,'Noni', 'Jenney', 'Agender', 'Brazil'),
(278,'Malory', 'Willock', 'Female', 'Indonesia'),
(279,'Fernanda', 'Barlass', 'Female', 'Vietnam'),
(280,'Dena', 'Lochrie', 'Genderfluid', 'Indonesia'),
(281,'Isador', 'Mattimoe', 'Male', 'China'),
(282,'Roscoe', 'Burnie', 'Male', 'Ukraine'),
(283,'Kristal', 'Bines', 'Female', 'Philippines'),
(284,'Chan', 'Duddridge', 'Male', 'Brazil'),
(285,'Rhody', 'Buxam', 'Female', 'France'),
(286,'Reagan', 'Denning', 'Male', 'China'),
(287,'Seline', 'McAlinden', 'Female', 'Ukraine'),
(289,'Minette', 'Carlet', 'Female', 'Japan'),
(290,'Phil', 'Pilbeam', 'Female', 'France'),
(291,'Celestine', 'Exposito', 'Female', 'Hungary'),
(292,'Orv', 'Rennison', 'Male', 'China'),
(293,'Artie', 'Noyce', 'Male', 'Uganda'),
(294,'Katti', 'Burnsall', 'Female', 'Cameroon'),
(295,'Barbara', 'Ivakin', 'Female', 'Colombia'),
(296,'Danna', 'Maxfield', 'Female', 'Panama'),
(297,'Jenine', 'Dominighi', 'Female', 'Austria'),
(298,'Winn', 'Stubbeley', 'Male', 'France'),
(299,'Brit', 'Doldon', 'Female', 'Egypt'),
(300,'Birgitta', 'Sorby', 'Female', 'Botswana')

	select * from cricketers

insert into cricketers(cricketers_id,first_name,last_name,gender,country) values(301,'Arlinda', 'Chadwick', 'Female', 'China'),
(302,'Liv', 'Weyland', 'Female', 'Cuba'),
(303,'Carree', 'Romei', 'Female', 'Indonesia'),
(304,'Red', 'Shooter', 'Male', 'Brazil'),
(305,'Lorna', 'Caldwell', 'Female', 'China'),
(306,'Antony', 'Creany', 'Male', 'Canada'),
(307,'Fanny', 'MacAfee', 'Female', 'Sweden'),
(308,'Joeann', 'Donnelly', 'Female', 'Peru'),
(309,'Wynny', 'Carey', 'Female', 'Croatia'),
(310,'Suzann', 'Brechin', 'Female', 'Tunisia'),
(311,'Jenica', 'Bracci', 'Female', 'China'),
(312,'Jessi', 'Lesly', 'Female', 'Brazil'),
(313,'Davita', 'Western', 'Female', 'Vietnam'),
(314,'Nichol', 'Macieiczyk', 'Female', 'Kyrgyzstan'),
(315,'Philis', 'Edgeon', 'Female', 'Syria'),
(316,'Martie', 'Denyer', 'Male', 'Philippines'),
(317,'Russell', 'Sircomb', 'Male', 'Greece'),
(318,'Virgilio', 'Leaf', 'Polygender', 'Philippines'),
(319,'Zach', 'McKibbin', 'Male', 'Russia'),
(320,'Baron', 'MacKinnon', 'Male', 'Japan'),
(321,'Blakeley', 'Cunney', 'Female', 'Chile'),
(322,'Emmaline', 'Gostall', 'Female', 'China'),
(323,'Morgen', 'Elliman', 'Male', 'France'),
(324,'Regan', 'Ecclestone', 'Female', 'Honduras'),
(325,'Ingrim', 'Foot', 'Male', 'Colombia'),
(326,'Anastassia', 'Woodwing', 'Female', 'China'),
(327,'Reilly', 'Thow', 'Male', 'China'),
(328,'Arnie', 'D''Ugo', 'Male', 'Indonesia'),
(329,'Ozzy', 'Karpychev', 'Polygender', 'Indonesia'),
(330,'Ernestus', 'De Domenicis', 'Genderqueer', 'Indonesia'),
(331,'Jannel', 'McAster', 'Female', 'Ethiopia'),
(332,'Hurlee', 'Markovich', 'Male', 'Indonesia'),
(333,'Shayla', 'Ridgedell', 'Polygender', 'Kyrgyzstan'),
(334,'Babbette', 'Jurs', 'Female', 'Poland'),
(335,'Merla', 'Robatham', 'Female', 'Argentina'),
(336,'Valina', 'Towlson', 'Female', 'Honduras'),
(337,'Marcellina', 'Napolione', 'Female', 'Pakistan'),
(338,'Jackqueline', 'Butler', 'Female', 'Argentina'),
(339,'Lowrance', 'Sanday', 'Male', 'Venezuela'),
(340,'Maurice', 'Davidman', 'Male', 'Argentina'),
(341,'Gardener', 'Laytham', 'Male', 'France'),
(342,'Nealy', 'Marchent', 'Male', 'Japan'),
(343,'Harman', 'Ghilardi', 'Male', 'Palestinian Territory'),
(345,'Berne', 'Luquet', 'Male', 'New Caledonia'),
(346,'Hatty', 'Halden', 'Female', 'Argentina'),
(347,'Catherin', 'Coffee', 'Female', 'Finland'),
(348,'Sybila', 'Cotherill', 'Female', 'Poland'),
(349,'Neill', 'Schimmang', 'Male', 'Indonesia'),
(350,'Jarid', 'Pottberry', 'Male', 'Svalbard and Jan Mayen'),
(351,'Cassandry', 'Wisham', 'Female', 'Argentina'),
(352,'Dorolisa', 'Dureden', 'Female', 'China'),
(353,'Darby', 'Paggitt', 'Polygender', 'Egypt'),
(354,'Isabelle', 'Lightoller', 'Female', 'Germany'),
(355,'Costa', 'Deyes', 'Male', 'South Africa'),
(356,'Fionna', 'Harker', 'Non-binary', 'Thailand'),
(357,'Horatius', 'Lafontaine', 'Male', 'Germany'),
(358,'Christoffer', 'MacCarroll', 'Male', 'Czech Republic'),
(359,'Jewel', 'Archibald', 'Female', 'Peru'),
(360,'Shell', 'Yanshin', 'Agender', 'Argentina'),
(361,'Bernardine', 'Bennis', 'Female', 'Serbia'),
(362,'Kaitlyn', 'Toderbrugge', 'Female', 'China'),
(363,'Sile', 'Le Galle', 'Female', 'Brazil'),
(364,'Davine', 'Crockley', 'Female', 'Poland'),
(365,'Zitella', 'Cato', 'Female', 'Poland'),
(366,'Arleyne', 'Hovenden', 'Female', 'Japan'),
(367,'Kristine', 'Hodjetts', 'Female', 'Albania'),
(368,'Vail', 'Matas', 'Male', 'China'),
(369,'Kimberly', 'Cure', 'Genderqueer', 'Thailand'),
(370,'Jeromy', 'Minifie', 'Male', 'Russia'),
(371,'Neils', 'Scanlin', 'Male', 'Thailand'),
(372,'Windy', 'Mougel', 'Female', 'Slovenia'),
(373,'Leupold', 'English', 'Male', 'Ukraine'),
(374,'Flinn', 'Larsen', 'Male', 'China'),
(375,'Sheree', 'Vane', 'Female', 'Portugal'),
(376,'Boone', 'Ravenscroftt', 'Genderqueer', 'China'),
(378,'Gabriello', 'Tomkowicz', 'Male', 'China'),
(379,'Eugenie', 'Mercy', 'Female', 'Portugal'),
(380,'Frederigo', 'Growcock', 'Male', 'Russia'),
(381,'Jewell', 'Sandham', 'Female', 'Russia'),
(382,'Lexie', 'Ivanikhin', 'Female', 'France'),
(383,'Kalil', 'Hartin', 'Male', 'Thailand'),
(384,'Thaddeus', 'Marshman', 'Male', 'Argentina'),
(385,'Laurel', 'Sirr', 'Female', 'Mexico'),
(386,'Yank', 'Sandyfirth', 'Bigender', 'China'),
(387,'Liliane', 'Mines', 'Female', 'Honduras'),
(388,'Noam', 'Tredget', 'Male', 'Czech Republic'),
(389,'Gordie', 'Testo', 'Male', 'Germany'),
(390,'Haze', 'Nadin', 'Male', 'China'),
(391,'Gibbie', 'Gowry', 'Male', 'Philippines'),
(392,'Myrle', 'Lathleiff', 'Female', 'Georgia'),
(393,'Barby', 'McQuarter', 'Female', 'Vietnam'),
(394,'Sydney', 'MacCague', 'Male', 'Poland'),
(395,'Madelon', 'Goucher', 'Female', 'Colombia'),
(396,'Caroline', 'Huntar', 'Female', 'Czech Republic'),
(397,'Samara', 'Asaaf', 'Female', 'Venezuela'),
(398,'Cinnamon', 'Lytell', 'Female', 'France'),
(399,'Edward', 'Rettie', 'Male', 'Suriname'),
(400,'Gray', 'Wallenger', 'Female', 'Indonesia')

	select * from cricketers
	
insert into cricketers(cricketers_id,first_name,last_name,gender,country) values(401,'Demeter', 'Beavis', 'Female', 'Indonesia'),
(402,'Evelyn', 'Callow', 'Female', 'Portugal'),
(403,'Wayland', 'Kobu', 'Male', 'Indonesia'),
(404,'Genevra', 'Lago', 'Female', 'Ukraine'),
(405,'Lucienne', 'Brager', 'Female', 'Indonesia'),
(406,'Edna', 'Vanin', 'Female', 'China'),
(407,'Chrissy', 'Pickering', 'Male', 'Indonesia'),
(408,'Emelina', 'Hollibone', 'Female', 'Vietnam'),
(409,'Robin', 'Bryns', 'Male', 'Portugal'),
(410,'Jay', 'Martill', 'Male', 'Portugal'),
(411,'Garvey', 'Lorenzini', 'Male', 'South Africa'),
(412,'Salomi', 'Pointing', 'Female', 'Latvia'),
(413,'Isidro', 'Scotting', 'Male', 'Indonesia'),
(414,'Judon', 'Stutard', 'Male', 'Myanmar'),
(415,'Barry', 'O'' Reagan', 'Male', 'United States'),
(416,'Earlie', 'Korbmaker', 'Genderfluid', 'Burkina Faso'),
(417,'Felita', 'Jeal', 'Female', 'Tunisia'),
(418,'Claude', 'de Werk', 'Female', 'Colombia'),
(419,'Rollo', 'Ownsworth', 'Male', 'Peru'),
(420,'Etienne', 'Bletsoe', 'Agender', 'Portugal'),
(421,'Becki', 'MacSwayde', 'Female', 'China'),
(423,'Ryun', 'Elverstone', 'Male', 'United Arab Emirates'),
(424,'Gladi', 'Madden', 'Female', 'Indonesia'),
(425,'Agatha', 'Feek', 'Female', 'China'),
(426,'Neilla', 'Boxhall', 'Female', 'Malaysia'),
(427,'Gabby', 'Hutchings', 'Male', 'China'),
(428,'Elli', 'Janikowski', 'Female', 'Palestinian Territory'),
(429,'Lida', 'Frail', 'Female', 'Ecuador'),
(430,'Gwennie', 'Leggott', 'Female', 'China'),
(431,'Miller', 'Christopher', 'Male', 'United States'),
(432,'Mord', 'Hayer', 'Male', 'China'),
(433,'Alfons', 'Canton', 'Male', 'France'),
(434,'Graeme', 'Tanfield', 'Male', 'Indonesia'),
(435,'Nerte', 'Whitworth', 'Female', 'Indonesia'),
(436,'Donnie', 'Tempest', 'Female', 'Pakistan'),
(437,'Terry', 'Molnar', 'Male', 'China'),
(438,'Saleem', 'Baybutt', 'Agender', 'Latvia'),
(439,'Anestassia', 'Joan', 'Female', 'Indonesia'),
(440,'Dotti', 'Woltering', 'Female', 'Poland'),
(441,'Bette', 'Rikard', 'Female', 'Serbia'),
(442,'Billy', 'Nancekivell', 'Male', 'Mexico'),
(443,'Caron', 'Fayer', 'Female', 'Ethiopia'),
(444,'Ameline', 'Towey', 'Female', 'Japan'),
(445,'Dal', 'Flanigan', 'Male', 'China'),
(446,'Phaidra', 'Smale', 'Female', 'Peru'),
(447,'Lonnard', 'Weall', 'Male', 'China'),
(448,'Lu', 'Le - Count', 'Female', 'Philippines'),
(449,'Rodger', 'Rosenau', 'Male', 'Japan'),
(450,'Alyse', 'Blakeney', 'Female', 'Poland'),
(451,'Manolo', 'Benitez', 'Male', 'China'),
(452,'Rowe', 'Abrahamoff', 'Female', 'Brazil'),
(453,'Randie', 'Fronzek', 'Male', 'Poland'),
(454,'Wye', 'Elliot', 'Male', 'China'),
(455,'Reynard', 'Janicijevic', 'Male', 'China'),
(456,'Richart', 'Scorrer', 'Male', 'China'),
(457,'Bank', 'Harfleet', 'Male', 'Brazil'),
(458,'Natty', 'Cassimer', 'Male', 'Greece'),
(459,'Abie', 'Hamlin', 'Male', 'Saudi Arabia'),
(460,'Donaugh', 'Bricket', 'Male', 'Ethiopia'),
(461,'Cyrill', 'Weildish', 'Male', 'China'),
(462,'Rik', 'Alessandretti', 'Male', 'Russia'),
(463,'Nissa', 'Dhenin', 'Non-binary', 'Portugal'),
(464,'Fred', 'Jerdon', 'Male', 'United States'),
(465,'Pebrook', 'Comer', 'Male', 'Brazil'),
(466,'Babs', 'Platt', 'Non-binary', 'Japan'),
(467,'Gard', 'Tribell', 'Male', 'China'),
(468,'Ellsworth', 'Anderton', 'Male', 'China'),
(469,'Idaline', 'Bark', 'Female', 'Indonesia'),
(470,'Jamill', 'Josefsen', 'Male', 'Czech Republic'),
(471,'Winslow', 'Lang', 'Male', 'France'),
(472,'Dominique', 'Baumann', 'Bigender', 'Russia'),
(473,'Roxana', 'MacDearmid', 'Female', 'Brazil'),
(474,'Lamont', 'Stayt', 'Male', 'China'),
(475,'Ertha', 'Gamble', 'Female', 'Uruguay'),
(476,'Clovis', 'O''Canavan', 'Female', 'China'),
(477,'Herta', 'Sully', 'Female', 'Ukraine'),
(479,'Brittney', 'Snarr', 'Genderfluid', 'Venezuela'),
(480,'Cyrille', 'Hebner', 'Male', 'Albania'),
(481,'Freeman', 'Decruse', 'Male', 'Indonesia'),
(482,'Davidson', 'Coo', 'Bigender', 'Bulgaria'),
(483,'Rosalind', 'Fost', 'Polygender', 'Colombia'),
(484,'Miquela', 'Shackell', 'Female', 'Brazil'),
(485,'Wallie', 'Torrans', 'Male', 'Azerbaijan'),
(486,'Arabella', 'de la Tremoille', 'Female', 'China'),
(487,'Robbyn', 'Mortimer', 'Female', 'United States'),
(488,'Filmer', 'Shalloo', 'Male', 'China'),
(489,'Had', 'McNally', 'Male', 'Indonesia'),
(490,'Larry', 'Falconer-Taylor', 'Male', 'Sweden'),
(491,'Ysabel', 'Lilburne', 'Female', 'Finland'),
(492,'Karina', 'Degoey', 'Female', 'South Korea'),
(493,'Meriel', 'Alliot', 'Female', 'China'),
(494,'Keefer', 'Stubbings', 'Agender', 'Malaysia'),
(495,'Alard', 'Lote', 'Male', 'China'),
(496,'Devlin', 'Pickett', 'Male', 'France'),
(497,'Stafford', 'Gannaway', 'Male', 'China'),
(498,'Shadow', 'Hender', 'Male', 'United States'),
(499,'Doretta', 'Shemmin', 'Female', 'China'),
(500,'Baryram', 'Cumpton', 'Male', 'Philippines')

	select * from cricketers
	
insert into cricketers(cricketers_id,first_name,last_name,gender,country) values(501,'Lambert', 'Eathorne', 'Male', 'Philippines'),
(502,'Maible', 'Dorking', 'Female', 'China'),
(503,'Alicia', 'Cavie', 'Female', 'Japan'),
(504,'Binky', 'Fellenor', 'Bigender', 'United States'),
(505,'Claire', 'McConnell', 'Female', 'Russia'),
(506,'Tracy', 'Castagno', 'Female', 'Spain'),
(507,'Port', 'Staden', 'Male', 'Ghana'),
(508,'Kermie', 'Bollam', 'Male', 'Philippines'),
(509,'Des', 'Rubinek', 'Male', 'China'),
(510,'Deeanne', 'Currier', 'Female', 'China'),
(511,'Eleonore', 'Hubber', 'Female', 'Philippines'),
(512,'Harmonie', 'Vlasenko', 'Female', 'Gabon'),
(513,'Marysa', 'Yokel', 'Female', 'Gabon'),
(514,'Philippa', 'Dubose', 'Female', 'Canada'),
(515,'Prentiss', 'Blodget', 'Male', 'Thailand'),
(516,'Venita', 'McCurrie', 'Female', 'Uruguay'),
(517,'Bat', 'McIlwraith', 'Male', 'Namibia'),
(518,'Bryant', 'Howkins', 'Bigender', 'Portugal'),
(519,'Zack', 'De Dei', 'Male', 'Afghanistan'),
(520,'Elroy', 'Warnock', 'Male', 'China'),
(521,'Temple', 'Gegg', 'Male', 'Colombia'),
(522,'Rivi', 'Scrimgeour', 'Female', 'Poland'),
(523,'Shannan', 'Maryman', 'Male', 'Indonesia'),
(524,'Erminia', 'Svanini', 'Female', 'France'),
(525,'Vanni', 'Salandino', 'Genderqueer', 'Uzbekistan'),
(526,'Skylar', 'Chaudhry', 'Polygender', 'Greece'),
(527,'Lizzie', 'Loughlin', 'Female', 'Kazakhstan'),
(528,'Gilda', 'Diggell', 'Female', 'United States'),
(529,'Bud', 'Sydry', 'Genderfluid', 'China'),
(530,'Oona', 'Marcham', 'Female', 'Indonesia'),
(531,'Maxie', 'Willock', 'Female', 'Indonesia'),
(532,'Neysa', 'Pearde', 'Female', 'North Korea'),
(533,'Ava', 'Hyndman', 'Genderqueer', 'Philippines'),
(534,'Bettine', 'Dunstone', 'Female', 'Greece'),
(535,'Dalt', 'Cicchinelli', 'Male', 'Indonesia'),
(536,'Marsiella', 'Morecombe', 'Female', 'Syria'),
(537,'Maximo', 'Ropkins', 'Male', 'East Timor'),
(538,'Ronny', 'Nazair', 'Female', 'Philippines'),
(539,'Aeriell', 'Meneghelli', 'Female', 'Iran'),
(540,'Consolata', 'Reavell', 'Female', 'Brazil'),
(541,'Jana', 'O''Duane', 'Female', 'China'),
(542,'Saidee', 'Canto', 'Female', 'Serbia'),
(543,'Oralla', 'Shillum', 'Female', 'China'),
(544,'Hillary', 'Hought', 'Male', 'Indonesia'),
(545,'Rafael', 'Niset', 'Genderqueer', 'Saint Lucia'),
(546,'Ileane', 'Doulton', 'Female', 'Colombia'),
(547,'Ahmad', 'Bellelli', 'Male', 'Portugal'),
(548,'Haven', 'Paddefield', 'Male', 'Peru'),
(549,'Tully', 'Heyburn', 'Male', 'Latvia'),
(550,'Westbrook', 'Kennea', 'Male', 'Russia'),
(551,'Kerwinn', 'Smout', 'Male', 'Czech Republic'),
(552,'Lyndy', 'Tocque', 'Female', 'Russia'),
(553,'Baron', 'Prigmore', 'Male', 'Portugal'),
(554,'Lenard', 'Binks', 'Male', 'Philippines'),
(555,'Kylie', 'Thame', 'Female', 'Indonesia'),
(556,'Fredek', 'Stein', 'Male', 'China'),
(557,'Alexandro', 'Rothert', 'Male', 'Sweden'),
(558,'Leigh', 'Kermitt', 'Male', 'Azerbaijan'),
(559,'Devonna', 'Galtone', 'Female', 'Nigeria'),
(560,'Jocelyn', 'Cattle', 'Female', 'Thailand'),
(561,'Albie', 'Marskell', 'Male', 'Russia'),
(562,'Udale', 'Emmer', 'Male', 'Ukraine'),
(563,'Eryn', 'Bignal', 'Female', 'Argentina'),
(564,'Francisca', 'Robiot', 'Female', 'China'),
(565,'Amandi', 'Lowman', 'Female', 'Philippines'),
(566,'Cheston', 'Whistance', 'Polygender', 'China'),
(567,'Brinn', 'Yemm', 'Female', 'Sierra Leone'),
(568,'Consolata', 'Farndon', 'Female', 'France'),
(569,'Efren', 'Renish', 'Male', 'France'),
(570,'Karoline', 'Jukes', 'Female', 'China'),
(571,'Devondra', 'Guilloton', 'Genderfluid', 'Uganda'),
(572,'Abigale', 'Presser', 'Female', 'Poland'),
(573,'Peg', 'Corssen', 'Female', 'China'),
(574,'Marco', 'Stephenson', 'Male', 'Philippines'),
(575,'Valene', 'Corkett', 'Female', 'Portugal'),
(576,'Philippine', 'Gartin', 'Female', 'China'),
(577,'Joannes', 'Cowley', 'Female', 'Honduras'),
(578,'Arvin', 'Coare', 'Male', 'Poland'),
(579,'Cristabel', 'Hutsby', 'Female', 'Greece'),
(580,'Mikaela', 'Toplin', 'Female', 'Bosnia and Herzegovina'),
(581,'Bunni', 'Ruscoe', 'Female', 'Russia'),
(582,'Kayle', 'Zeal', 'Female', 'Thailand'),
(583,'Ree', 'Adiscot', 'Female', 'China'),
(584,'Kayla', 'Benbrick', 'Female', 'Russia'),
(585,'Erin', 'Corneille', 'Male', 'United States'),
(586,'Wilie', 'Hailey', 'Female', 'France'),
(587,'Leigh', 'Roubert', 'Female', 'Poland'),
(588,'Krystyna', 'Flooks', 'Female', 'Morocco'),
(589,'Guglielma', 'Menhci', 'Female', 'China'),
(590,'Rene', 'Chamney', 'Female', 'Philippines'),
(591,'Barry', 'Finlayson', 'Male', 'Vietnam'),
(592,'Olia', 'Miskin', 'Female', 'China'),
(593,'Niel', 'Eccleston', 'Male', 'United States'),
(594,'Dionis', 'Fincher', 'Agender', 'Armenia'),
(595,'Zacharie', 'Bellamy', 'Male', 'Indonesia'),
(596,'Ammamaria', 'Pedro', 'Female', 'China'),
(597,'Sebastiano', 'Moyes', 'Male', 'Russia'),
(598,'Donnie', 'Frampton', 'Male', 'Indonesia'),
(599,'Sim', 'Penwright', 'Male', 'Bolivia'),
(600,'Ceil', 'Pigeram', 'Female', 'Germany')

	select * from cricketers

insert into cricketers(cricketers_id,first_name,last_name,gender,country) values(601,'Gael', 'Grigoli', 'Female', 'Peru'),
(602,'Brand', 'Chipps', 'Male', 'Japan'),
(603,'Chloette', 'Fetherstan', 'Female', 'Philippines'),
(604,'Aksel', 'Bischoff', 'Male', 'China'),
(605,'Crin', 'Hoofe', 'Female', 'Indonesia'),
(606,'Milty', 'Ethridge', 'Male', 'Indonesia'),
(607,'Maddy', 'Howcroft', 'Polygender', 'Nigeria'),
(608,'Jeannie', 'Deniscke', 'Female', 'France'),
(609,'Bekki', 'Neller', 'Female', 'Finland'),
(610,'Rivi', 'La Croce', 'Female', 'United States'),
(611,'Rhodie', 'Brimner', 'Female', 'Portugal'),
(612,'Dicky', 'Winterbourne', 'Male', 'Philippines'),
(613,'Felisha', 'Lindgren', 'Female', 'Macedonia'),
(614,'Inness', 'Curm', 'Male', 'Croatia'),
(615,'Suzi', 'Kibard', 'Female', 'China'),
(616,'Alyosha', 'Walhedd', 'Male', 'France'),
(617,'Nance', 'Theaker', 'Female', 'Ecuador'),
(618,'John', 'Attwater', 'Polygender', 'Luxembourg'),
(619,'Osbourn', 'Beaven', 'Male', 'Philippines'),
(620,'Evvy', 'Kas', 'Female', 'China'),
(621,'Gerard', 'Chitty', 'Polygender', 'Indonesia'),
(622,'Alane', 'Shoppee', 'Female', 'China'),
(623,'Colby', 'Alishoner', 'Male', 'Portugal'),
(624,'Roderich', 'Dmitriev', 'Male', 'Indonesia'),
(625,'Eugen', 'Sheal', 'Male', 'Lithuania'),
(626,'Owen', 'Boscott', 'Male', 'Philippines'),
(627,'Alisha', 'Thurber', 'Female', 'Palestinian Territory'),
(628,'Nanice', 'Ascroft', 'Female', 'China'),
(629,'Warner', 'Wormleighton', 'Male', 'Sweden'),
(630,'Hasty', 'Klyner', 'Male', 'Russia'),
(631,'Linette', 'Arnau', 'Female', 'Bulgaria'),
(632,'Alta', 'Lipgens', 'Female', 'Portugal'),
(633,'Clarette', 'ducarme', 'Female', 'Belarus'),
(634,'Vittoria', 'Weyman', 'Female', 'Indonesia'),
(635,'Seward', 'Stollenbeck', 'Male', 'Israel'),
(636,'Jehu', 'Smullen', 'Male', 'Indonesia'),
(637,'Wallache', 'Beavington', 'Male', 'South Korea'),
(638,'Milton', 'Richold', 'Male', 'China'),
(639,'Ernaline', 'Wedderburn', 'Female', 'France'),
(640,'Hervey', 'Titchard', 'Male', 'Russia'),
(641,'Farrel', 'Lackham', 'Male', 'France'),
(642,'Lewes', 'Camois', 'Bigender', 'Libya'),
(643,'Erina', 'Wilkins', 'Female', 'China'),
(644,'Lauretta', 'Kenford', 'Female', 'China'),
(645,'Jourdain', 'Gersam', 'Male', 'Indonesia'),
(646,'Daron', 'Gubbin', 'Male', 'Peru'),
(647,'Dora', 'Warratt', 'Female', 'China'),
(648,'Rodrick', 'Huxstep', 'Male', 'Russia'),
(649,'Kort', 'Rudderham', 'Male', 'Indonesia'),
(650,'Patti', 'Dalloway', 'Female', 'Indonesia'),
(651,'Phillida', 'Dillamore', 'Genderfluid', 'Japan'),
(652,'Paola', 'Ghilardini', 'Female', 'South Korea'),
(653,'Jdavie', 'Brody', 'Male', 'Poland'),
(654,'Caleb', 'Linfoot', 'Male', 'France'),
(655,'Velma', 'Pilkington', 'Female', 'Chile'),
(656,'Kessia', 'Irnis', 'Female', 'Poland'),
(657,'Brockie', 'Yoxen', 'Male', 'Russia'),
(658,'Neill', 'Bahike', 'Male', 'Argentina'),
(659,'Gennie', 'Benediktsson', 'Female', 'China'),
(660,'Raymond', 'Roback', 'Male', 'Armenia'),
(661,'Edan', 'Grishunin', 'Male', 'Ukraine'),
(662,'Haroun', 'Schlagtmans', 'Male', 'Bulgaria'),
(663,'Mead', 'Eusden', 'Female', 'Syria'),
(664,'Fidela', 'Rooke', 'Female', 'Japan'),
(665,'Alie', 'Travers', 'Female', 'Venezuela'),
(666,'Kelley', 'Noakes', 'Male', 'United Kingdom'),
(667,'Talya', 'De Ferrari', 'Female', 'Peru'),
(668,'Avivah', 'Di Filippo', 'Female', 'Sierra Leone'),
(669,'Alphonso', 'Kenn', 'Male', 'Vietnam'),
(670,'Olivero', 'Fiander', 'Male', 'Indonesia'),
(671,'Ernie', 'Willmott', 'Male', 'Philippines'),
(672,'Cathi', 'Jeandillou', 'Female', 'Nicaragua'),
(673,'Manfred', 'Dunkerley', 'Male', 'China'),
(674,'Calida', 'Rann', 'Female', 'China'),
(675,'Anatol', 'Dancey', 'Male', 'Georgia'),
(676,'Dolores', 'Stairmand', 'Female', 'Norway'),
(677,'Joaquin', 'Hurdis', 'Male', 'Colombia'),
(678,'Ailbert', 'Hunnable', 'Male', 'Poland'),
(679,'Patrice', 'Danielsky', 'Male', 'China'),
(680,'Darius', 'Lescop', 'Male', 'China'),
(681,'Kit', 'Louthe', 'Female', 'Philippines'),
(682,'Ally', 'Cankett', 'Genderqueer', 'Sweden'),
(683,'Roda', 'Louden', 'Female', 'Norway'),
(684,'Langsdon', 'Strangeways', 'Polygender', 'China'),
(685,'Adolphe', 'Clowney', 'Male', 'Brazil'),
(686,'Filmore', 'MacAdam', 'Non-binary', 'Nigeria'),
(687,'Shayna', 'Harm', 'Female', 'Russia'),
(688,'Jordain', 'O''Brogane', 'Female', 'Philippines'),
(689,'Allard', 'Hebbard', 'Male', 'China'),
(690,'Danielle', 'Pauletto', 'Female', 'Finland'),
(691,'Merle', 'Giacopello', 'Female', 'Russia'),
(692,'Jesse', 'Aloshikin', 'Female', 'Luxembourg'),
(693,'Boigie', 'Laboune', 'Male', 'Cambodia'),
(694,'Nowell', 'Yanson', 'Male', 'Armenia'),
(695,'Moise', 'Renol', 'Male', 'Madagascar'),
(696,'Dagny', 'MacPeake', 'Male', 'Yemen'),
(697,'Simone', 'Frape', 'Male', 'Moldova'),
(698,'Torey', 'Brunner', 'Female', 'United States'),
(699,'Jillene', 'Penbarthy', 'Female', 'Uganda'),
(700,'Gordy', 'Tomasz', 'Male', 'United States')

	select * from cricketers
	
insert into cricketers(cricketers_id,first_name,last_name,gender,country) values(701,'Stacey', 'Kulic', 'Female', 'Honduras'),
(702,'Georgeanna', 'Hanaby', 'Female', 'Brazil'),
(703,'Ayn', 'Clapperton', 'Female', 'China'),
(704,'Ogden', 'Werndley', 'Male', 'Sierra Leone'),
(705,'Michelle', 'Keable', 'Female', 'Philippines'),
(706,'Goldy', 'Broom', 'Female', 'Poland'),
(707,'Kip', 'Penticoot', 'Genderfluid', 'France'),
(708,'Emmerich', 'Mabee', 'Male', 'Indonesia'),
(709,'Doyle', 'Betteney', 'Male', 'Japan'),
(710,'Lukas', 'Broughton', 'Male', 'Vietnam'),
(711,'Bing', 'Favill', 'Male', 'Brazil'),
(712,'Christye', 'Stevenson', 'Bigender', 'Netherlands'),
(713,'Marianna', 'Pardue', 'Female', 'Poland'),
(714,'Quinlan', 'Town', 'Male', 'Nicaragua'),
(715,'Jerri', 'Huckabe', 'Male', 'France'),
(716,'Miran', 'Josephy', 'Female', 'Philippines'),
(717,'Selma', 'Kadar', 'Female', 'Niger'),
(718,'Danielle', 'Makepeace', 'Female', 'Philippines'),
(719,'Georgiana', 'Whelpdale', 'Female', 'Sweden'),
(720,'Tabby', 'Owain', 'Female', 'Nigeria'),
(721,'Ebony', 'MacPaike', 'Female', 'Indonesia'),
(722,'Christoper', 'Hyndman', 'Male', 'Colombia'),
(723,'Dorie', 'Wesley', 'Female', 'China'),
(724,'Zacharie', 'McOmish', 'Male', 'El Salvador'),
(725,'Akim', 'Payn', 'Male', 'China'),
(726,'Niel', 'Cicchinelli', 'Male', 'Philippines'),
(727,'Jilli', 'Nield', 'Female', 'Indonesia'),
(728,'Sabra', 'Shillabear', 'Female', 'Indonesia'),
(729,'Kellina', 'Brick', 'Female', 'Indonesia'),
(730,'Kelvin', 'Renvoys', 'Male', 'Nepal'),
(731,'Julie', 'Davidove', 'Female', 'United States'),
(732,'Sheridan', 'Deetch', 'Male', 'Brazil'),
(733,'Austen', 'Murdie', 'Male', 'France'),
(734,'Geri', 'Iddins', 'Male', 'China'),
(735,'Fiorenze', 'Fennell', 'Female', 'Colombia'),
(736,'Jorry', 'Ceeley', 'Female', 'Czech Republic'),
(737,'Tim', 'Pocklington', 'Female', 'South Africa'),
(738,'Phylys', 'Swinn', 'Genderqueer', 'Japan'),
(739,'Eliot', 'Mulligan', 'Male', 'Finland'),
(740,'Nettie', 'Thoresbie', 'Female', 'United States'),
(741,'Tiffanie', 'Coldbath', 'Female', 'Russia'),
(742,'Sullivan', 'Cafferty', 'Male', 'China'),
(743,'Torry', 'Cicconetti', 'Male', 'Niger'),
(744,'Burnard', 'Pilley', 'Male', 'China'),
(745,'Franny', 'Snawdon', 'Male', 'Slovenia'),
(746,'Maris', 'Kirkman', 'Genderfluid', 'Colombia'),
(747,'Pandora', 'Gerge', 'Female', 'Russia'),
(748,'Ashla', 'Jeffry', 'Female', 'Mongolia'),
(749,'Mead', 'Summersby', 'Female', 'China'),
(750,'Isidoro', 'Lonnon', 'Male', 'Brazil'),
(751,'Shae', 'Toplin', 'Male', 'Nigeria'),
(752,'Otis', 'Meynell', 'Male', 'China'),
(753,'Ricca', 'Wrey', 'Female', 'United States'),
(754,'Ashlee', 'De Metz', 'Female', 'Canada'),
(755,'Dorothee', 'Deackes', 'Female', 'China'),
(756,'Angelia', 'Haeslier', 'Female', 'China'),
(757,'Tiertza', 'Ladewig', 'Genderqueer', 'Japan'),
(758,'Sharla', 'Batters', 'Female', 'Indonesia'),
(759,'Ann', 'Cawkill', 'Female', 'Tajikistan'),
(760,'Mariellen', 'Scragg', 'Female', 'Croatia'),
(761,'Tyler', 'Gemnett', 'Male', 'China'),
(762,'Normie', 'Frantz', 'Male', 'Portugal'),
(763,'Claudianus', 'Artist', 'Male', 'Slovenia'),
(764,'Shara', 'Stanett', 'Female', 'Indonesia'),
(765,'Kellsie', 'Carlos', 'Female', 'France'),
(766,'Merv', 'Runnicles', 'Male', 'Poland'),
(767,'Elena', 'Roxbrough', 'Bigender', 'China'),
(768,'Loutitia', 'Pretsell', 'Female', 'Japan'),
(769,'Arnuad', 'Garatty', 'Male', 'China'),
(770,'Alastair', 'Knapp', 'Male', 'Norway'),
(771,'Chancey', 'Loadman', 'Male', 'China'),
(772,'Tabby', 'Hauck', 'Female', 'United States'),
(773,'Damara', 'Buddington', 'Female', 'Colombia'),
(774,'Micah', 'Corless', 'Male', 'Brazil'),
(775,'Danyette', 'Beau', 'Female', 'China'),
(776,'Lotti', 'Lampens', 'Female', 'Kazakhstan'),
(777,'Belicia', 'Copner', 'Female', 'Philippines'),
(778,'Lambert', 'Studders', 'Male', 'China'),
(779,'Carmelle', 'Creagh', 'Bigender', 'China'),
(780,'Jarad', 'Finlow', 'Male', 'China'),
(781,'Fredrick', 'Sansome', 'Male', 'Japan'),
(782,'Barbee', 'Tocher', 'Female', 'Russia'),
(783,'Torrance', 'Blazey', 'Male', 'Philippines'),
(784,'Irving', 'Markl', 'Male', 'Portugal'),
(785,'Raphaela', 'Ellesworth', 'Female', 'Ireland'),
(786,'Hillyer', 'Chellam', 'Male', 'China'),
(787,'Martha', 'Assad', 'Female', 'China'),
(788,'Nita', 'Petkov', 'Female', 'China'),
(789,'Jamaal', 'Wille', 'Male', 'Montenegro'),
(790,'Orelie', 'MacAllen', 'Female', 'Greece'),
(791,'Dianemarie', 'Glitherow', 'Female', 'China'),
(792,'Melody', 'Mathissen', 'Female', 'Philippines'),
(793,'Elenore', 'Beine', 'Female', 'China'),
(794,'Irving', 'Ricardet', 'Male', 'Morocco'),
(795,'Hadley', 'Tremayne', 'Male', 'China'),
(796,'Josias', 'Somerled', 'Polygender', 'Russia'),
(797,'Lebbie', 'Rowthorn', 'Female', 'France'),
(798,'Letizia', 'Figgess', 'Female', 'Russia'),
(799,'Helyn', 'Seed', 'Female', 'Russia'),
(800,'Tremayne', 'Repp', 'Male', 'Colombia')

	select * from cricketers
	
insert into cricketers(cricketers_id,first_name,last_name,gender,country) values(801,'Cynthie', 'Viste', 'Female', 'China'),
(802,'Arlette', 'McNamee', 'Female', 'Portugal'),
(803,'Timmie', 'Bate', 'Female', 'Zimbabwe'),
(804,'Winnie', 'Behnke', 'Male', 'Russia'),
(805,'Myron', 'Bowland', 'Male', 'Faroe Islands'),
(806,'Quentin', 'Battams', 'Female', 'Brazil'),
(807,'Witty', 'Bacon', 'Male', 'China'),
(808,'Forester', 'Scrace', 'Genderqueer', 'Brazil'),
(809,'Mayne', 'Choules', 'Male', 'Thailand'),
(810,'Wini', 'Naseby', 'Female', 'China'),
(811,'Jed', 'Shuxsmith', 'Bigender', 'Bulgaria'),
(812,'Tedda', 'Douglass', 'Female', 'Norway'),
(813,'Neely', 'Purshouse', 'Female', 'China'),
(814,'Anestassia', 'Idell', 'Female', 'Indonesia'),
(815,'Griz', 'Prestner', 'Male', 'Philippines'),
(816,'Frederic', 'Shakelady', 'Polygender', 'China'),
(817,'Sanders', 'Sheldon', 'Male', 'Russia'),
(818,'Sonnie', 'Monument', 'Bigender', 'Philippines'),
(819,'Winnah', 'Cutill', 'Female', 'Russia'),
(820,'Alfi', 'Wythe', 'Female', 'Russia'),
(821,'Lyon', 'Hagan', 'Male', 'Russia'),
(822,'Keefe', 'Munro', 'Male', 'China'),
(823,'Lucky', 'Gadney', 'Female', 'Czech Republic'),
(824,'Lilian', 'Noble', 'Female', 'Greece'),
(825,'Beitris', 'Shinner', 'Female', 'Ukraine'),
(826,'Barbaraanne', 'Martinuzzi', 'Female', 'China'),
(827,'Lisabeth', 'Thring', 'Female', 'Central African Republic'),
(828,'Giselle', 'McGarvey', 'Female', 'United States'),
(829,'Robby', 'Ivakhno', 'Female', 'Nigeria'),
(830,'Westbrooke', 'Doneld', 'Male', 'Philippines'),
(831,'Maury', 'Evershed', 'Male', 'Brazil'),
(832,'Lois', 'Gridon', 'Female', 'China'),
(833,'Janeta', 'Eddies', 'Female', 'Palestinian Territory'),
(834,'Glenda', 'Bycraft', 'Female', 'Japan'),
(835,'Harrison', 'L''Homme', 'Male', 'China'),
(836,'Borg', 'Hendonson', 'Male', 'Syria'),
(837,'Sharai', 'Benmore', 'Female', 'Poland'),
(838,'Sybille', 'Girardoni', 'Female', 'China'),
(839,'Marco', 'MacParland', 'Male', 'Guatemala'),
(840,'Roman', 'Beers', 'Male', 'Sweden'),
(841,'Glynn', 'Kelshaw', 'Genderfluid', 'Philippines'),
(842,'Gene', 'Gorch', 'Male', 'Czech Republic'),
(843,'Chloris', 'Bestwick', 'Female', 'China'),
(844,'Stanly', 'Foulkes', 'Genderqueer', 'Russia'),
(845,'Ade', 'Beese', 'Male', 'Brazil'),
(846,'Trixi', 'Cornuau', 'Agender', 'Colombia'),
(847,'Carmelita', 'Morriss', 'Female', 'Indonesia'),
(848,'Pascal', 'Corsor', 'Male', 'Sweden'),
(849,'Yul', 'Maggill''Andreis', 'Male', 'Palestinian Territory'),
(850,'Sarah', 'Koomar', 'Female', 'Iran'),
(851,'Thaddeus', 'Wiggans', 'Male', 'China'),
(852,'Cris', 'Dagless', 'Male', 'Thailand'),
(853,'Rem', 'Pennycook', 'Male', 'Indonesia'),
(854,'Glynnis', 'Dossettor', 'Female', 'Serbia'),
(855,'Issie', 'Hubbocks', 'Female', 'Italy'),
(856,'Arel', 'Jahn', 'Male', 'Philippines'),
(857,'Lowe', 'MacCosty', 'Male', 'Russia'),
(858,'Selina', 'Kelberman', 'Female', 'Indonesia'),
(859,'Ellwood', 'Gavini', 'Male', 'Vietnam'),
(860,'Stevy', 'Sotheron', 'Male', 'Tunisia'),
(861,'Marigold', 'Simunek', 'Female', 'France'),
(862,'Norene', 'von Nassau', 'Female', 'Ukraine'),
(863,'Maxim', 'Harwick', 'Bigender', 'Sweden'),
(864,'Imogen', 'Mayho', 'Female', 'Vietnam'),
(865,'Daven', 'Scraggs', 'Male', 'Portugal'),
(866,'Abbey', 'Buckingham', 'Male', 'Laos'),
(867,'Berk', 'Alesbrook', 'Male', 'China'),
(868,'Dot', 'Havis', 'Genderfluid', 'Brazil'),
(869,'Nilson', 'Murrigan', 'Male', 'Philippines'),
(870,'Killy', 'MacKill', 'Male', 'China'),
(871,'Audrie', 'Weson', 'Genderqueer', 'Zambia'),
(872,'Garner', 'Breese', 'Male', 'China'),
(873,'Bidget', 'Furmston', 'Female', 'China'),
(874,'Nev', 'Pinnick', 'Male', 'Vietnam'),
(875,'Arch', 'Meneer', 'Male', 'Bulgaria'),
(876,'Seth', 'Doldon', 'Male', 'Russia'),
(877,'Eadmund', 'Grieger', 'Male', 'Sweden'),
(878,'Royce', 'McNern', 'Male', 'Syria'),
(879,'Stephana', 'Lattie', 'Female', 'Bulgaria'),
(880,'Doralyn', 'Vala', 'Female', 'Thailand'),
(881,'Tirrell', 'Wapol', 'Genderqueer', 'Portugal'),
(882,'Debi', 'Colleymore', 'Bigender', 'Peru'),
(883,'Gareth', 'Brailsford', 'Male', 'Indonesia'),
(884,'Worth', 'Fouldes', 'Male', 'China'),
(885,'Drew', 'Ibell', 'Male', 'United States'),
(886,'Stacy', 'Bloodworth', 'Male', 'United States'),
(887,'Alford', 'Dennis', 'Male', 'Pakistan'),
(888,'Vanda', 'Ruppel', 'Female', 'Canada'),
(889,'Margy', 'Chesnay', 'Female', 'Russia'),
(890,'Kristofor', 'Brunroth', 'Male', 'Myanmar'),
(891,'Alessandro', 'Wisson', 'Male', 'Mexico'),
(892,'Killian', 'Maykin', 'Male', 'Philippines'),
(893,'Lanny', 'Halburton', 'Female', 'Portugal'),
(894,'Kipp', 'Slimme', 'Male', 'Indonesia'),
(895,'Horton', 'Haffard', 'Male', 'Cuba'),
(896,'Ugo', 'Martelet', 'Male', 'Poland'),
(897,'Leia', 'Eastmond', 'Female', 'Czech Republic'),
(898,'Falito', 'Farn', 'Male', 'Sweden'),
(899,'Eran', 'Wafer', 'Female', 'China'),
(900,'Heda', 'Vasyushkhin', 'Female', 'South Africa')

	select * from cricketers 
	
insert into cricketers(cricketers_id,first_name,last_name,gender,country) values(901,'Alec', 'Frankes', 'Male', 'China'),
(902,'Titos', 'Ebi', 'Male', 'Indonesia'),
(903,'Mireielle', 'Durtnall', 'Female', 'Netherlands'),
(904,'Johanna', 'Van Der Vlies', 'Genderfluid', 'Thailand'),
(905,'Haydon', 'Judson', 'Male', 'Finland'),
(906,'Elvin', 'Fairholm', 'Male', 'China'),
(907,'Jonell', 'Giovanardi', 'Female', 'Philippines'),
(908,'Jethro', 'McPhelimey', 'Male', 'United States'),
(909,'Drusi', 'Smittoune', 'Female', 'Russia'),
(910,'Laurie', 'Macenzy', 'Male', 'Bulgaria'),
(911,'Gabriellia', 'Edginton', 'Female', 'Indonesia'),
(912,'Rolland', 'Dwelling', 'Male', 'China'),
(913,'Blinnie', 'Danbrook', 'Female', 'Poland'),
(914,'Dreddy', 'Gillson', 'Female', 'Russia'),
(915,'Levi', 'deKnevet', 'Male', 'China'),
(916,'Raff', 'Beckey', 'Male', 'Indonesia'),
(917,'Dniren', 'Berresford', 'Bigender', 'Philippines'),
(918,'Remington', 'Fitzmaurice', 'Genderfluid', 'Japan'),
(919,'Isidore', 'Goodhand', 'Non-binary', 'China'),
(920,'Silas', 'MacGaughey', 'Male', 'Chad'),
(921,'Rheta', 'Hughlin', 'Female', 'China'),
(922,'Ella', 'Scanlin', 'Female', 'China'),
(923,'Merrile', 'Lacasa', 'Female', 'Russia'),
(924,'Kirk', 'McCaster', 'Male', 'Poland'),
(925,'Derrek', 'Rolland', 'Male', 'Japan'),
(926,'Crin', 'McEntagart', 'Female', 'Colombia'),
(927,'Jori', 'Burbank', 'Female', 'Sweden'),
(928,'Phyllida', 'Avrashin', 'Female', 'Poland'),
(929,'Klemens', 'Gerault', 'Male', 'Sweden'),
(930,'Jaquelyn', 'Relf', 'Polygender', 'Uzbekistan'),
(931,'Jorge', 'Barks', 'Male', 'Indonesia'),
(932,'Jorgan', 'Hartright', 'Male', 'Portugal'),
(933,'Giraldo', 'Leveridge', 'Male', 'South Africa'),
(934,'Jorry', 'Deverille', 'Female', 'Philippines'),
(935,'Prissie', 'Vipan', 'Female', 'China'),
(936,'Gar', 'Gilbertson', 'Male', 'Portugal'),
(937,'Lucas', 'De Simone', 'Male', 'Philippines'),
(938,'Amelina', 'McMurtyr', 'Female', 'France'),
(939,'Mollee', 'Gloves', 'Female', 'Panama'),
(940,'Meridith', 'Schlagh', 'Female', 'Mauritius'),
(941,'Karlan', 'Stanyland', 'Male', 'China'),
(942,'Bartie', 'Gamwell', 'Male', 'China'),
(943,'Maddy', 'Mence', 'Female', 'Afghanistan'),
(945,'Rollins', 'Winham', 'Agender', 'Peru'),
(946,'Matilda', 'Clemenceau', 'Female', 'Brazil'),
(947,'Kacey', 'Duffie', 'Female', 'Indonesia'),
(948,'Merna', 'Stell', 'Female', 'Georgia'),
(949,'Brigida', 'Duthie', 'Female', 'China'),
(950,'Allene', 'Sailor', 'Female', 'Vietnam'),
(951,'Nessy', 'Tinklin', 'Female', 'China'),
(952,'Kennith', 'Beaves', 'Male', 'China'),
(953,'Asa', 'McGourty', 'Male', 'Philippines'),
(954,'Skippie', 'Rockcliffe', 'Male', 'Thailand'),
(955,'Katheryn', 'Mackin', 'Female', 'Japan'),
(956,'Gavin', 'Ettritch', 'Genderqueer', 'China'),
(957,'Gilda', 'O'' Quirk', 'Female', 'Philippines'),
(958,'Engracia', 'Bluschke', 'Female', 'Poland'),
(959,'Rodolphe', 'Johanchon', 'Male', 'Portugal'),
(960,'Jory', 'Rhys', 'Male', 'Thailand'),
(961,'Vincent', 'Rudolf', 'Male', 'Chile'),
(962,'Vivienne', 'Battaille', 'Female', 'Portugal'),
(963,'Yancy', 'Lewing', 'Male', 'Indonesia'),
(964,'Vally', 'O''Carrol', 'Female', 'Dominican Republic'),
(965,'Corine', 'Askem', 'Female', 'Brazil'),
(966,'Ferrel', 'Beeres', 'Male', 'Ethiopia'),
(967,'Rickert', 'Custance', 'Male', 'Japan'),
(968,'Gussi', 'Astell', 'Female', 'United States'),
(969,'Hoebart', 'Latimer', 'Male', 'Brazil'),
(970,'Olvan', 'Velasquez', 'Male', 'Germany'),
(971,'Aubert', 'Conigsby', 'Male', 'Poland'),
(972,'Robbyn', 'Crittal', 'Female', 'East Timor'),
(973,'Kerianne', 'Pennock', 'Female', 'Ecuador'),
(974,'Gilberte', 'Bauduccio', 'Female', 'Vietnam'),
(975,'Krissie', 'Gratland', 'Female', 'Paraguay'),
(976,'Chandra', 'Ivankovic', 'Female', 'Colombia'),
(977,'Devondra', 'Sproston', 'Female', 'Indonesia'),
(978,'Scarlet', 'Tournie', 'Female', 'Chile'),
(979,'Ida', 'Powys', 'Female', 'Philippines'),
(980,'Shaun', 'Windle', 'Male', 'Brazil'),
(981,'Ferdie', 'Trenam', 'Male', 'Venezuela'),
(982,'Hallie', 'Crowe', 'Genderqueer', 'Mexico'),
(983,'Susan', 'O'' Culligan', 'Genderfluid', 'Spain'),
(984,'Dyna', 'Arlt', 'Female', 'China'),
(985,'Jodi', 'Stoney', 'Female', 'Japan'),
(986,'Tate', 'Douche', 'Male', 'China'),
(987,'Meris', 'Fernao', 'Female', 'Slovenia'),
(988,'Farand', 'Wilce', 'Bigender', 'France'),
(989,'Gerri', 'Piggford', 'Female', 'Indonesia'),
(990,'Sampson', 'Pietron', 'Male', 'Sweden'),
(991,'Augustus', 'Onraet', 'Male', 'South Africa'),
(992,'Emmet', 'Vuitte', 'Male', 'China'),
(993,'Boonie', 'Staton', 'Male', 'Brazil'),
(994,'Cher', 'Grebbin', 'Female', 'Russia'),
(995,'Shani', 'Midgley', 'Female', 'Indonesia'),
(996,'Corette', 'Lowell', 'Female', 'Uzbekistan'),
(997,'Tobe', 'Garmey', 'Male', 'Afghanistan'),
(998,'Emmanuel', 'Ollett', 'Male', 'France'),
(999,'Mandie', 'Ricco', 'Female', 'Vietnam'),
(1000,'Roxane', 'Chilley', 'Female', 'Brazil')

	select * from cricketers
	
